"""initial_schema_patents_processing_logs_embeddings_meta

Revision ID: 0af0082fe330
Revises: 
Create Date: 2026-07-23 13:15:07.199092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0af0082fe330'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patents',
    sa.Column('patent_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patent_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('claims', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('inventors', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('filing_date', sa.String(length=50), nullable=True),
    sa.Column('publication_date', sa.String(length=50), nullable=True),
    sa.Column('cpc_codes', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('ipc_codes', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('s3_key', sa.Text(), nullable=True),
    sa.Column('source_repository', sa.String(length=100), nullable=True),
    sa.Column('domain_tags', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('patent_id')
    )
    op.create_index(op.f('ix_patents_patent_number'), 'patents', ['patent_number'], unique=True)
    op.create_table('embeddings_meta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patent_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('section_name', sa.String(length=100), nullable=True),
    sa.Column('claim_number', sa.Integer(), nullable=True),
    sa.Column('vector_db_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.patent_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patent_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.patent_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processing_logs')
    op.drop_table('embeddings_meta')
    op.drop_index(op.f('ix_patents_patent_number'), table_name='patents')
    op.drop_table('patents')
    # ### end Alembic commands ###
